# Generated by Django 6.1 on 2026-09-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_avancado', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['titulo'], name='idx_livro_titulo'),
        ),
    ]
